# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cri/grpc-runtime/interrupt.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'cri/grpc-runtime/interrupt.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n cri/grpc-runtime/interrupt.proto\x12\x08\x63ri.grpc\"0\n\x0cPauseRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\"0\n\rPauseResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"!\n\rResumeRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\"1\n\x0eResumeResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\":\n\x0fRollbackRequest\x12\x15\n\rcheckpoint_id\x18\x01 \x01(\t\x12\x10\n\x08\x61gent_id\x18\x02 \x01(\t\"K\n\x10RollbackResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x16\n\x0erestored_files\x18\x03 \x03(\t2\xd3\x01\n\x10InterruptService\x12\x38\n\x05Pause\x12\x16.cri.grpc.PauseRequest\x1a\x17.cri.grpc.PauseResponse\x12;\n\x06Resume\x12\x17.cri.grpc.ResumeRequest\x1a\x18.cri.grpc.ResumeResponse\x12H\n\x0fTriggerRollback\x12\x19.cri.grpc.RollbackRequest\x1a\x1a.cri.grpc.RollbackResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cri.grpc_runtime.interrupt_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PAUSEREQUEST']._serialized_start=46
  _globals['_PAUSEREQUEST']._serialized_end=94
  _globals['_PAUSERESPONSE']._serialized_start=96
  _globals['_PAUSERESPONSE']._serialized_end=144
  _globals['_RESUMEREQUEST']._serialized_start=146
  _globals['_RESUMEREQUEST']._serialized_end=179
  _globals['_RESUMERESPONSE']._serialized_start=181
  _globals['_RESUMERESPONSE']._serialized_end=230
  _globals['_ROLLBACKREQUEST']._serialized_start=232
  _globals['_ROLLBACKREQUEST']._serialized_end=290
  _globals['_ROLLBACKRESPONSE']._serialized_start=292
  _globals['_ROLLBACKRESPONSE']._serialized_end=367
  _globals['_INTERRUPTSERVICE']._serialized_start=370
  _globals['_INTERRUPTSERVICE']._serialized_end=581
# @@protoc_insertion_point(module_scope)
