# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from cri.grpc_runtime import interrupt_pb2 as cri_dot_grpc__runtime_dot_interrupt__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cri/grpc_runtime/interrupt_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InterruptServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Pause = channel.unary_unary(
                '/cri.grpc.InterruptService/Pause',
                request_serializer=cri_dot_grpc__runtime_dot_interrupt__pb2.PauseRequest.SerializeToString,
                response_deserializer=cri_dot_grpc__runtime_dot_interrupt__pb2.PauseResponse.FromString,
                _registered_method=True)
        self.Resume = channel.unary_unary(
                '/cri.grpc.InterruptService/Resume',
                request_serializer=cri_dot_grpc__runtime_dot_interrupt__pb2.ResumeRequest.SerializeToString,
                response_deserializer=cri_dot_grpc__runtime_dot_interrupt__pb2.ResumeResponse.FromString,
                _registered_method=True)
        self.TriggerRollback = channel.unary_unary(
                '/cri.grpc.InterruptService/TriggerRollback',
                request_serializer=cri_dot_grpc__runtime_dot_interrupt__pb2.RollbackRequest.SerializeToString,
                response_deserializer=cri_dot_grpc__runtime_dot_interrupt__pb2.RollbackResponse.FromString,
                _registered_method=True)


class InterruptServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Pause(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Resume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerRollback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InterruptServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Pause': grpc.unary_unary_rpc_method_handler(
                    servicer.Pause,
                    request_deserializer=cri_dot_grpc__runtime_dot_interrupt__pb2.PauseRequest.FromString,
                    response_serializer=cri_dot_grpc__runtime_dot_interrupt__pb2.PauseResponse.SerializeToString,
            ),
            'Resume': grpc.unary_unary_rpc_method_handler(
                    servicer.Resume,
                    request_deserializer=cri_dot_grpc__runtime_dot_interrupt__pb2.ResumeRequest.FromString,
                    response_serializer=cri_dot_grpc__runtime_dot_interrupt__pb2.ResumeResponse.SerializeToString,
            ),
            'TriggerRollback': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerRollback,
                    request_deserializer=cri_dot_grpc__runtime_dot_interrupt__pb2.RollbackRequest.FromString,
                    response_serializer=cri_dot_grpc__runtime_dot_interrupt__pb2.RollbackResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cri.grpc.InterruptService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cri.grpc.InterruptService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InterruptService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Pause(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cri.grpc.InterruptService/Pause',
            cri_dot_grpc__runtime_dot_interrupt__pb2.PauseRequest.SerializeToString,
            cri_dot_grpc__runtime_dot_interrupt__pb2.PauseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Resume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cri.grpc.InterruptService/Resume',
            cri_dot_grpc__runtime_dot_interrupt__pb2.ResumeRequest.SerializeToString,
            cri_dot_grpc__runtime_dot_interrupt__pb2.ResumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerRollback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cri.grpc.InterruptService/TriggerRollback',
            cri_dot_grpc__runtime_dot_interrupt__pb2.RollbackRequest.SerializeToString,
            cri_dot_grpc__runtime_dot_interrupt__pb2.RollbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
