apiVersion: 1

datasources:
  - name: CRI Postgres
    type: postgres
    uid: cri-postgres
    access: proxy
    url: postgres:5432
    database: cri_runtime
    user: cri_admin
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
