apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cri-runtime-default-deny
  namespace: cri-runtime
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53

