apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cri-runtime-job-executor
  namespace: cri-runtime
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cri-runtime-job-executor
  namespace: cri-runtime
subjects:
  - kind: ServiceAccount
    name: cri-runtime
    namespace: cri-runtime
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cri-runtime-job-executor

